version: "3.8"
services:
  db:
    image: 'postgres:14'
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
    restart: always

  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./env/flask.env
    stdin_open: true
    tty: true
    depends_on:
      - db

